# Generated by Django 2.2.5 on 2019-09-27 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inteligence', '0002_measure'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Measure',
            new_name='Imeasure',
        ),
        migrations.RenameModel(
            old_name='sintom',
            new_name='Isintom',
        ),
        migrations.RenameModel(
            old_name='Zone',
            new_name='Izone',
        ),
    ]
