# Generated by Django 2.2.5 on 2019-09-23 15:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateTimeField(blank=True, null=True)),
                ('date_end', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(max_length=100)),
                ('diagnostic', models.TextField(blank=True, null=True)),
                ('userpk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_consulta', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserGeneral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_birth', models.IntegerField()),
                ('gender', models.CharField(choices=[('m', 'Masculino'), ('f', 'Femenino')], max_length=20)),
                ('userpk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_general', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sintom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sintoma', models.CharField(max_length=200)),
                ('zona', models.CharField(max_length=20)),
                ('causa', models.TextField(blank=True, null=True)),
                ('consultapk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultapk', to='webapp.Consulta')),
            ],
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicamento', models.CharField(max_length=200)),
                ('cuantity', models.CharField(max_length=200)),
                ('regularity', models.CharField(max_length=100)),
                ('temporarity', models.CharField(max_length=100)),
                ('consultapk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consulta_medication', to='webapp.Consulta')),
            ],
        ),
        migrations.CreateModel(
            name='HealthInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elemento', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('allergie', 'Alergia'), ('cronic', 'Cronic'), ('indication', 'Indication')], max_length=20)),
                ('userpk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_health', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
