# Generated by Django 2.2.5 on 2019-09-27 15:37

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usergeneral',
            old_name='year_birth',
            new_name='age',
        ),
        migrations.AddField(
            model_name='usergeneral',
            name='name',
            field=models.CharField(default=datetime.datetime(2019, 9, 27, 15, 37, 1, 984846, tzinfo=utc), max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='healthinfo',
            name='userpk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_health', to='webapp.UserGeneral'),
        ),
    ]
