# Generated by Django 2.2.5 on 2019-10-09 17:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0002_auto_20190927_1537'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserGeneral',
            new_name='Patient',
        ),
    ]
