# Generated by Django 2.2.5 on 2019-10-09 17:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20191009_1731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulta',
            name='userpk',
        ),
        migrations.AddField(
            model_name='consulta',
            name='paciente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pacientepk', to='webapp.Patient'),
            preserve_default=False,
        ),
    ]
