# Generated by Django 2.2.5 on 2019-10-09 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20191009_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='sintom',
            name='intensidad',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='sintom',
            name='tipo',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='sintom',
            name='causa',
            field=models.TextField(blank=True, default='unknow', null=True),
        ),
        migrations.AlterField(
            model_name='sintom',
            name='sintoma',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='sintom',
            name='zona',
            field=models.TextField(blank=True, null=True),
        ),
    ]
