# Generated by Django 2.2.5 on 2019-10-09 19:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0006_auto_20191009_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='attend',
            field=models.ForeignKey(blank=True, null=True, on_delete=None, related_name='atendido', to=settings.AUTH_USER_MODEL),
        ),
    ]
