# Generated by Django 2.2.5 on 2019-10-10 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0007_consulta_attend'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consulta',
            old_name='diagnostic',
            new_name='hipotesis',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='attend',
        ),
        migrations.RemoveField(
            model_name='medication',
            name='consultapk',
        ),
        migrations.AlterField(
            model_name='consulta',
            name='status',
            field=models.CharField(max_length=10),
        ),
        migrations.CreateModel(
            name='Attend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnostic', models.TextField()),
                ('attended', models.ForeignKey(on_delete=None, related_name='attender', to=settings.AUTH_USER_MODEL)),
                ('consulta_attended', models.ForeignKey(on_delete='', related_name='consulta_atendida', to='webapp.Consulta')),
            ],
        ),
        migrations.AddField(
            model_name='medication',
            name='attender',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='attend_medication', to='webapp.Attend'),
            preserve_default=False,
        ),
    ]
