# Generated by Django 2.2.5 on 2019-10-10 16:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0008_auto_20191010_1605'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speciality', models.TextField()),
                ('title', models.TextField()),
                ('contactinfo', models.TextField()),
                ('userpk', models.ForeignKey(on_delete=None, related_name='medic_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
