# Generated by Django 2.2.5 on 2019-10-11 02:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_auto_20191010_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='date_start',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
