# Generated by Django 2.2.5 on 2019-10-14 20:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_auto_20191011_0248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attend',
            name='consulta_attended',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consulta_atendida', to='webapp.Consulta'),
        ),
        migrations.AlterField(
            model_name='medic',
            name='userpk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medic_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
