# Generated by Django 2.2 on 2020-03-03 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_auto_20191014_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='medic',
            name='keywords',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medic',
            name='location',
            field=models.TextField(blank=True, null=True),
        ),
    ]
