# Generated by Django 2.2.2 on 2020-03-12 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0015_medicsym'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speciality', models.CharField(default='General', max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='medic',
            name='speciality',
        ),
        migrations.CreateModel(
            name='SpecialMedic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_up', models.IntegerField(default=100)),
                ('medicpk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Medic')),
                ('special', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Specialist')),
            ],
        ),
        migrations.CreateModel(
            name='Prediagnostic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.TextField(blank=True, null=True)),
                ('predg', models.CharField(max_length=500)),
                ('level_up', models.IntegerField(default=100)),
                ('special', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Specialist')),
            ],
        ),
    ]
