# Generated by Django 2.2 on 2020-03-12 23:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0017_auto_20200312_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='userapply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pacientepk', to=settings.AUTH_USER_MODEL),
        ),
    ]
