# Generated by Django 2.2 on 2020-03-12 23:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0018_auto_20200312_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='userapply',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='paciente_pk', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
